# Generated by Django 4.1.7 on 2023-06-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_profil_nikibu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posyandu',
            name='ke',
        ),
        migrations.AddField(
            model_name='posyandu',
            name='bulan',
            field=models.CharField(default='Januari', max_length=20),
        ),
    ]
