# Generated by Django 4.1.7 on 2023-06-23 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_posyandu_ke_posyandu_bulan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posyandu',
            old_name='nik',
            new_name='nama',
        ),
    ]
