# Generated by Django 4.1.7 on 2023-06-25 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profil_nikibu_profil_tempat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='tempat',
            new_name='dusun',
        ),
    ]
